# Generated by Django 2.2.6 on 2019-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
