# Generated by Django 2.2.6 on 2019-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0005_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
