# Generated by Django 2.2.6 on 2019-10-23 13:08

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img.noImage.png', upload_to=products.models.upload_image_path),
        ),
    ]
