# Generated by Django 2.2.6 on 2019-10-24 11:47

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_auto_20191023_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/noImage.png', upload_to=products.models.upload_image_path),
        ),
    ]
